apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: answers-received
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: answers.received
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 604800000
