apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-scrape-config
  namespace: metrics
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: vmagent
data:
  scrape.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: analytics
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: analytics
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: users
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: user-service
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: answers
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: answers
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: scheduler
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: scheduler
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: telegram-api
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: telegram-api
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: recommender
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: recommender
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: clickhouse
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - dev
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: clickhouse
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: replace
            target_label: __address__
            regex: ([^:]+):9363
            replacement: $1:9363

      - job_name: kafka
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - kafka
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_strimzi_io_name]
            action: keep
            regex: kafka-kafka
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: replace
            target_label: __address__
            regex: ([^:]+):9404
            replacement: $1:9404
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
